name: instrumentation

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $pgql_db
      POSTGRES_USER: $pgql_user
      POSTGRES_PASSWORD: $pgql_psw
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
